/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_school21_model_MainModel */

#ifndef _Included_edu_school21_model_MainModel
#define _Included_edu_school21_model_MainModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_school21_model_MainModel
 * Method:    finalFunc
 * Signature: (Ljava/lang/String;[DD)I
 */
JNIEXPORT jint JNICALL Java_edu_school21_model_MainModel_finalFunc(
    JNIEnv *, jobject, jstring, jdoubleArray, jdouble);

/*
 * Class:     edu_school21_model_MainModel
 * Method:    validX
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_school21_model_MainModel_validX(JNIEnv *,
                                                                jobject,
                                                                jstring);

/*
 * Class:     edu_school21_model_MainModel
 * Method:    validInput
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_edu_school21_model_MainModel_validInput(JNIEnv *, jobject, jstring);

/*
 * Class:     edu_school21_model_MainModel
 * Method:    per_month_ann
 * Signature: (DDI[D[D[D)V
 */
JNIEXPORT void JNICALL Java_edu_school21_model_MainModel_per_1month_1ann(
    JNIEnv *, jobject, jdouble, jdouble, jint, jdoubleArray, jdoubleArray,
    jdoubleArray);

/*
 * Class:     edu_school21_model_MainModel
 * Method:    per_month_diff
 * Signature: (DDI[D[D[D[D)V
 */
JNIEXPORT void JNICALL Java_edu_school21_model_MainModel_per_1month_1diff(
    JNIEnv *, jobject, jdouble, jdouble, jint, jdoubleArray, jdoubleArray,
    jdoubleArray, jdoubleArray);

typedef enum type_t {
  Number = 1,
  var_x = 2,
  left_bracket = 3,
  right_bracket = 4,
  op_plus = 5,
  op_minus = 6,
  op_mul = 7,
  op_div = 8,
  op_mod = 9,
  op_power = 10,
  f_sin = 11,
  f_cos = 12,
  f_tan = 13,
  f_asin = 14,
  f_acos = 15,
  f_atan = 16,
  f_sqrt = 17,
  f_ln = 18,
  f_log = 19
} my_type;

typedef struct Stack {
  double value;
  int priority;
  my_type type;
  struct Stack *next;
} Stack;

int valid_input(char *input);
void trim_input(char *input, char *result);
int valid_x(char *input);
int brackets_par(char *input);
int brackets_valid_in(char *input, size_t i);
int is_bracket(char symbol);
int bracket_after_func(char *input);

int is_operator(char *input, size_t *i, int offset);
int valid_after_operator(char *input);
int valid_after_mod(char *input);
int valid_mul(char *input);
int valid_simple_mul(char *input, size_t i);
int valid_complex_mul(char *input, size_t *i);
int valid_start(char *input);

int funcs(char *input, size_t *i, int offset);
int trigonometry(char *input, size_t *i, int offset);

int is_dot(char *input, int i);
int is_x(char symbol);
int is_number(char symbol);
int valid_number(char *input);

void push_node(Stack **head, double value, int priority, my_type type);
void pop_node(Stack **head);
int peek_node(Stack *head);
void remove_node(Stack **head);

int get_priority(my_type type);
int get_type_simple(char symbol);
int get_type_complex(char *input, size_t *i);

void stack_from_str(Stack **node, char *input, double x);
void simple_symbols(Stack **node, char symbol, double x);
void complex_symbols(Stack **node, char *input, size_t *i);
void number_symbols(Stack **node, char *input, size_t *i);
void inverse_stack(Stack **input, Stack **result);

void first_part_notation(Stack **origin, Stack **result, Stack **support,
                         int *k);
void second_part_notation(Stack **origin, Stack **result, Stack **support,
                          int *k);
void notation_stack(Stack **origin, Stack **result, Stack **support);

int calculate(Stack **ready, double *result);
void calculate_1(Stack **ready, Stack **number, int *flag_error_math);
void calculate_2(Stack **ready, Stack **number, int *flag_error_math);
void calculate_3(Stack **ready, Stack **number, int *flag_error_math);
void calculate_4(Stack **ready, Stack **number, int *flag_error_math);
int final_func(char *input, double *calculated, double x);

#ifdef __cplusplus
}
#endif
#endif
